
services:
  kibana:
    container_name: kibana
    image:  docker.elastic.co/kibana/kibana:7.3.0
    environment:
      SERVER_NAME: kibana.log
      ELASTICSEARCH_HOSTS: "http://elasticsearch.example.org:9200"
