services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    hostname: "rabbitmq"
    container_name: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      - "NAME=rabbitmq"
    volumes:
      - "./data:/var/lib/rabbitmq:delegated"
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
#      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
#      - "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"
